name: pesanmakan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Mengubah versi SDK agar lebih kompatibel

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  
  # Database dan Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.18
  intl: ^0.18.0

  cupertino_icons: ^1.0.8 
  flutter_local_notifications: ^18.0.1
  qr_code_scanner: ^0.4.0
  crypto: ^3.0.6
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Tools untuk generate code
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  
  flutter_lints: ^2.0.0  # Menurunkan versi lints untuk kompatibilitas

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.png
    - assets/foto.jpg
    - assets/resto.jpeg